added buttons to switch from coordinates and place name, crated new v…
aawad1/geolocation pull request #2
Opened 2024-02-11 16:05 UTC by aawad1

…iew for coordinates

2024-02-19 15:05 UTC, mehmedkadric commented on env copy/pyvenv.cfg
This file doesn't belong to github

2024-02-19 15:05 UTC, mehmedkadric commented on env copy/Scripts/Activate.ps1
These files don't belong to github (env copy, env folders, scripts folder and all files in it)

2024-02-19 15:06 UTC, mehmedkadric commented on main/migrations/0002_geolocatorstats_latitude_geolocatorstats_longitude.py
This file doesn't belong to github (migrations folder in general)

2024-02-19 17:33 UTC, mehmedkadric requested changes

2024-02-19 17:33 UTC, mehmedkadric commented on main/forms.py
> +        fields=["query", "latitude", "longitude"]
Why lat lon?

2024-02-19 17:33 UTC, mehmedkadric commented on main/static/css/my_styles.css
> +/* your_styles.css */
Common name for main css file is `style.css`.

2024-02-19 17:33 UTC, mehmedkadric commented on main/static/images/pexels-aksonsat-uanthoeng-10788502.jpg
Read about handling static files with Django. Did you use `python manage.py collectstatic` command? (E.g. set DEBUG=False and see how your app looks like). Ping me in private if you need more info on this.

2024-02-19 17:33 UTC, mehmedkadric commented on main/templates/coordinates.html
> +    function redirectToName() {
Perhaps you can use `href` tag instead having this function? Something like `href={% url 'homepage' %}` (not sure about syntax).

2024-02-19 17:33 UTC, mehmedkadric commented on main/templates/history.html
> +            <td class="text-light">{{item.id}}</td>
Are you sure we don't want to use for loop counter here? Just an idea: use pagination.

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
> +                    form.instance.query = fwg[0].get('name')
We talked about this. Create 'manually' a new record in the database with all necessary attributes.

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
>  def index(request):
Consider having multiple functions for handling different cases.
if condition1:
  function1()
 elif condition2:
  function2()
else:
  functionElse()

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
> +    except ValueError:
Investigate how to handle exceptions in Python. Check for function decorators and error handling (Initial resources: ChatGPT, https://www.geeksforgeeks.org/error-handling-in-python-using-decorators/ ).

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
> +######################################
What is the purpose of this line?

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
> +    # Your view logic goes here
What is the purpose of this line?

2024-02-19 17:33 UTC, mehmedkadric commented on main/views.py
> +            return render(request, 'coordinates.html', {"form": form, "place_name": reverse_geocode(latitude, longitude)[0]})
Maybe define context variable first (too much code in a single line here).

2024-02-19 18:01 UTC, aawad1 commented on main/views.py
> +######################################
just for me to see what is "data"

2024-02-24 12:59 UTC, mehmedkadric approved these changes

2024-02-27 09:33 UTC, closed without merging